const char* ocl_src_stars = 
" \n"
"\n"
"\n"
"constant float time_step = 0.01f;\n"
"constant float mass = 0.00009f;\n"
"constant float radius = 0.05f;\n"
"constant float repulsion = 0.5f;\n"
"\n"
"\n"
"unsigned long indx(unsigned long i, unsigned long j)\n"
"{\n"
"	return (j * (j - 1) / 2 + i);\n"
"}\n"
"\n"
"\n"
"kernel void propagate(global float4* pos, global float4* vel, global float* acc_matr)\n"
"{\n"
"	unsigned long i = get_global_id(0);\n"
"\n"
"	pos[i] = pos[i] + (float4)(time_step * vel[i].xyz, 0.0f);\n"
"\n"
"	if (length(pos[i].xyz) > 1.0f)\n"
"	{\n"
"		float3 pos_norm = normalize(pos[i].xyz);\n"
"		pos[i] = (float4)(2.0f * pos_norm - pos[i].xyz, 1.0f);\n"
"		vel[i] = (float4)(vel[i].xyz - dot(pos_norm, vel[i].xyz) * pos_norm, 0.0f);\n"
"	}\n"
"\n"
"	barrier(CLK_GLOBAL_MEM_FENCE);\n"
"\n"
"	for (unsigned long j = i + 1; j < get_global_size(0); j++)\n"
"	{\n"
"		float r = distance(pos[i], pos[j]);\n"
"\n"
"		if (r > radius)\n"
"		{\n"
"			acc_matr[indx(i, j)] = mass / r / r / r;\n"
"		}\n"
"		else\n"
"		{\n"
"			acc_matr[indx(i, j)] = -repulsion;\n"
"		}\n"
"	}\n"
"\n"
"	barrier(CLK_GLOBAL_MEM_FENCE);\n"
"\n"
"	float4 acc = (float4)(0.0f, 0.0f, 0.0f, 0.0f);\n"
"	for (unsigned long j = 0; j < i; j++)\n"
"	{\n"
"		acc += acc_matr[indx(j, i)] * (pos[j] - pos[i]);\n"
"	}\n"
"	for (unsigned long j = i + 1; j < get_global_size(0); j++)\n"
"	{\n"
"		acc += acc_matr[indx(i, j)] * (pos[j] - pos[i]);\n"
"	}\n"
"\n"
"	vel[i] = vel[i] + time_step * acc;\n"
"\n"
"	if (length(vel[i]) > 1.0f)\n"
"		vel[i] = normalize(vel[i]);\n"
"}\n"
"\0";
