const char* ocl_src_stars = 
"/*\n"
"	Copyright (C) 2019 Matej Gomboc https://github.com/MatejGomboc/Galaxy-Simulator\n"
"\n"
"	This program is free software: you can redistribute it and/or modify\n"
"	it under the terms of the GNU Affero General Public License as published\n"
"	by the Free Software Foundation, either version 3 of the License, or\n"
"	(at your option) any later version. This program is distributed in the\n"
"	hope that it will be useful, but WITHOUT ANY WARRANTY; without even the\n"
"	implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n"
"	See the GNU Affero General Public License for more details. You should\n"
"	have received a copy of the GNU Affero General Public License along with\n"
"	this program. If not, see <https://www.gnu.org/licenses/>.\n"
"*/\n"
"\n"
"\n"
"unsigned long indx(unsigned long i, unsigned long j)\n"
"{\n"
"	return (j * (j - 1) / 2 + i);\n"
"}\n"
"\n"
"\n"
"kernel void propagate(global float4* pos, global float4* vel, global float* acc_matr)\n"
"{\n"
"	constant float step = 0.01f;\n"
"	constant float mass = 0.00009f;\n"
"\n"
"	unsigned long i = get_global_id(0);\n"
"\n"
"	pos[i] = pos[i] + (float4)(step * vel[i].xyz, 0.0f);\n"
"\n"
"	if (length(pos[i].xyz) > 1.0f)\n"
"	{\n"
"		float3 pos_norm = normalize(pos[i].xyz);\n"
"		pos[i] = (float4)(2.0f * pos_norm - pos[i].xyz, 1.0f);\n"
"		vel[i] = (float4)(vel[i].xyz - dot(pos_norm, vel[i].xyz) * pos_norm, 0.0f);\n"
"	}\n"
"\n"
"	barrier(CLK_GLOBAL_MEM_FENCE);\n"
"\n"
"	for (unsigned long j = i + 1; j < get_global_size(0); j++)\n"
"	{\n"
"		float r = distance(pos[i], pos[j]);\n"
"\n"
"		if (r > 0.05f)\n"
"		{\n"
"			acc_matr[indx(i, j)] = mass / r / r / r;\n"
"		}\n"
"		else\n"
"		{\n"
"			acc_matr[indx(i, j)] = -0.5f;\n"
"		}\n"
"	}\n"
"\n"
"	barrier(CLK_GLOBAL_MEM_FENCE);\n"
"\n"
"	float4 acc = (float4)(0.0f, 0.0f, 0.0f, 0.0f);\n"
"	for (unsigned long j = 0; j < i; j++)\n"
"	{\n"
"		acc += acc_matr[indx(j, i)] * (pos[j] - pos[i]);\n"
"	}\n"
"	for (unsigned long j = i + 1; j < get_global_size(0); j++)\n"
"	{\n"
"		acc += acc_matr[indx(i, j)] * (pos[j] - pos[i]);\n"
"	}\n"
"\n"
"	vel[i] = vel[i] + step * acc;\n"
"\n"
"	if (length(vel[i]) > 1.0f)\n"
"		vel[i] = normalize(vel[i]);\n"
"}\n"
"\0";
